//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalProveedoresMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BioOrdenesCompra
    {
        public string Documento { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Estatus { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public double SubTotal { get; set; }
        public double Impuesto { get; set; }
        public double Total { get; set; }
        public string Tienda { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string RIF { get; set; }
        public string Observacion { get; set; }
    }
}
