//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalProveedoresMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BioOrdenesCompraDetalle
    {
        public string Documento { get; set; }
        public string RIF { get; set; }
        public string Producto { get; set; }
        public double Cantidad { get; set; }
        public double Costo { get; set; }
        public double SubTotal { get; set; }
        public double Impuesto { get; set; }
        public double Total { get; set; }
        public double CantidadRecibida { get; set; }
        public int Linea { get; set; }
        public string CodigoProducto { get; set; }
        public string Presentacion { get; set; }
        public Nullable<int> Bultos { get; set; }
        public double Kg { get; set; }
        public Nullable<double> UnidadesOdc { get; set; }
        public double CantPresentacion { get; set; }
    }
}
