//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalProveedoresMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BioProveedores
    {
        public string RIF { get; set; }
        public string Proveedor { get; set; }
        public string Tipo { get; set; }
        public int Afiliado { get; set; }
        public Nullable<int> DDNId { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string BioMail { get; set; }
        public string Telefono { get; set; }
        public string Codigo { get; set; }
    }
}
