//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalProveedoresMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BioRetencionFacturas
    {
        public string Factura { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Proveedor { get; set; }
        public string RIF { get; set; }
        public double Retencion { get; set; }
        public double SubTotal { get; set; }
        public double Impuesto { get; set; }
        public double MontoTotalFactura { get; set; }
        public double BaseImponible { get; set; }
        public string Concepto { get; set; }
        public string TipoRetencion { get; set; }
        public double MontoBase { get; set; }
        public double Porcentaje { get; set; }
        public double MontoRetencion { get; set; }
        public string Correlativo { get; set; }
        public string NoControl { get; set; }
        public decimal CodRetencion { get; set; }
        public string ConceptoRetencion { get; set; }
    }
}
